### ISSUE TITLE
Linux builds in the future? 

### ISSUE THREAD

**Issue by raygervais** [VASTDynamics/Vaporizer2#1]
Love that you've open sourced Vaporizor2, I used to play with it when I was on Windows. These days, I find myself like many others using Linux (Debian in this case) as their daily driver. Would love to help get a Linux build which works with Bitwig Studio working! 

Thanks!

**Comment by KottV** [comment]
for impatient ones:
https://github.com/KottV/Vaporizer2/tree/linux-fixes
https://github.com/KottV/Vaporizer2/blob/linux-fixes/LINUX_BUILD.md

**Comment by VASTDynamics** [comment]
@KottV Could you please contact me at tobias@vast-dynamics.com about merging this into the main branch? Thx.

**Comment by mikelupe** [comment]
Thank you both for your efforts. 

@KottV for Linux, your hint about the "disable GFX" setting was golden, as I got not only performance issues, but reproducable crashes/segfaults with Ardour. when being accelerated. Apparently the multithreaded OpenGL through JUCE leads to that, one of the main Ardour devs was speculating.

Disabling it made it work smoothly.

**Comment by VASTDynamics** [comment]
Merged in beta

**Comment by RustoMCSpit** [comment]
are linux builds available, i dont see them in releases?

**Comment by RustoMCSpit** [comment]
https://software.opensuse.org/download.html?project=multimedia%3Aproaudio&package=vaporizer2

apparently this is where linux is for now
