### ISSUE TITLE
Factory and User data folder.

### ISSUE THREAD

**Issue by KottV** [VASTDynamics/Vaporizer2#12]
Vaporizer2 uses only one set of directories for storing factory presets(tables/samples), that goes with installer and for the user created stuff. To make this possible in Windows the installer sets the target directory access as `everyone-full` on `Program Files\Vaporizer2`.
In theory `Program Files` shouldn't be write-accessible to users. And in Linux/Unix such approach is not allowed, assuming that data set is stored in the default `/usr/share/Vaporizer2` directory, afaik it's the case for MacOS also.

If the software is installed with system-wide installer or package manager there is no(proper)  way to put data in user's directory during installation, as we don't know who/how many users will use it. It's possible to check then copy a whole data to the user's dir at start of Vaporizer2 but it multiplies the disk usage space.

Perfect solution for that could be the handling of both paths, the factory (read-only) and the user dir.

**Comment by VASTDynamics** [comment]
Yes, we need to change the folder structures as described here:
[](https://docs.juce.com/master/tutorial_app_plugin_packaging.html )
Working on it.

**Comment by KottV** [comment]
Actually I think that problem is a bit deeper than just changing default folders.
By using `/usr/share/Vaporizer2` I mean that `Presets` `Noises` `Tables` from Vaporizer2 installer  goes there and this directory is read-only. The same is for other OSes using their appropriate  paths.
If I want to save the Preset, then it will be placed in my home directory, like `~/Documents/Vaporizer2/Presets`. So we have two path variables  - Factory and User, and both should be available in Preset browser.

Yes, it complicates the code, but I'm ready to contribute to this feature.

**Comment by VASTDynamics** [comment]
Yes, let's jointly fix that in beta. Thank you.

**Comment by VASTDynamics** [comment]
@KottV  I think we do not need two separate paths in the preset browser. I would suggest to always install the factory (presets, wavetables, noises) as today in the App folder (e.g. c:\Program Files\Vaporizer2 ...). The folders in the preset browser would be the user folders then. The installer would create them e.g. under ~/Documents/Vaporizer2 for Linux. The plugin would need to merge factory and user content then. This would also guarantee compatibility with what is already there. What do you think?

**Comment by KottV** [comment]
>The plugin would need to merge factory and user content then.

How it would be merged? I mean, is it a copying from factory folder to user's one. Or it's a parsing both folders in the code?

**Comment by VASTDynamics** [comment]
I meant the second option. At least for presets. The preset browser already works with multiple folders and subfolders. Presets store the full path internally, Adding seprate factory and user fodler structures would be easy. 
```
        FileSearchPath sPath = FileSearchPath(myProcessor->m_UserPresetRootFolder);
        Array<File> presetFiles;
        sPath.findChildFiles(presetFiles, File::findFiles, true, "*.vvp");
```
https://github.com/VASTDynamics/Vaporizer2/blob/b13762447de9b263067c2e16995efa14968adef0/VASTvaporizer/Source/Plugin/VASTPreset/VASTPresetData.cpp#L70C1-L72C68

For wavetables and samples / noises it is more difficult (and is it needed?) since here I use the standard OS file open dialog.

**Comment by KottV** [comment]
> E.g. simply this works and adds all presets from G:\presets to the list::
Oh great!

I'm not sure about copying noises/tables, I believe you here :)
But these operations, like copying files and userdir creation should be done by the plugin, because installer may not know which user profile to use, and in *nix world the package manager doesn't do anything in user dirs, but with system directories like `/usr` only.

**Comment by KottV** [comment]
@gnac  would you like to join this discussion?

there is a quick attempt to make default user preset directory in `~/Documents` https://github.com/KottV/Vaporizer2/commits/userdir

**Comment by KottV** [comment]
@VASTDynamics 
what I suggest:
1. Use common variable path for the `VASTvaporizerSettings.xml` file on all platforms, it will be `~/.config/Vaporizer2` in Linux, `C:\Users\<username>\AppData\Roaming\Vaporizer2` in Windows and `~/Library/Vaporizer2` on Mac:
`juce::File::getSpecialLocation(File::userApplicationDataDirectory).getChildFile("Vaporizer2").getChildFile(settingsFile).getFullPathName();`

2. Use `Documents` folder as default for Presets on all platforms (may be overridden in settings):
`juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("Vaporizer2").getFullPathName();`

3. search for the Factory Presets in the `/usr/share/Vaporizer2` in Linux:
`juce::File::getSpecialLocation(juce::File::globalApplicationsDirectory).getChildFile("share/Vaporizer2").getFullPathName()`

4.  and search for Factory in `/Library/Vaporizer2` on Mac and `c:\ProgramData\Vaporizer2` on Windows:
`juce::File::getSpecialLocation(juce::File::commonApplicationDataDirectory).getChildFile("Vaporizer2").getFullPathName()`
 
 
JUCE reference : https://docs.juce.com/master/classFile.html#a3e19cafabb03c5838160263a6e76313d
diff in my repo:  https://github.com/KottV/Vaporizer2/compare/beta...userdir

**Comment by VASTDynamics** [comment]
I am working on this. For 1) I opt for:

```
String VASTAudioProcessor::getSettingsFilePath(bool read, bool &migrate_legacy) {
	const String settingsFile = "VASTvaporizerSettings.xml";
#ifdef JUCE_WINDOWS
	//JUCE>> File::getSpecialLocation(File::commonApplicationDataDirectory) ="C:\ProgramData"
	String filename = File::getSpecialLocation(File::commonApplicationDataDirectory).getFullPathName() + "\\Vaporizer2\\" + settingsFile;
	if (read) {
		if (!File(filename).existsAsFile()) {
			File(filename).create(); //recursively create also directories
			File(filename).deleteFile();
			filename = getVSTPath() + "\\VASTvaporizerSettings.xml"; //try compatibility
			migrate_legacy = true;
		}
	}
#elif JUCE_MAC
	//JUCE>> File::getSpecialLocation(File::commonApplicationDataDirectory) ="/Library"
	String filename = File::getSpecialLocation(File::commonApplicationDataDirectory).getFullPathName() + "/Application Support/Vaporizer2/" + settingsFile;
	if (read) {
		if (!File(filename).existsAsFile()) {
			File(filename).create(); //recursively create also directories
			File(filename).deleteFile();
			filename = getVSTPath() + "/VASTvaporizerSettings.xml"; //try compatibility
			migrate_legacy = true;
		}
	}
#elif JUCE_LINUX
	//JUCE>> File::getSpecialLocation(File::commonApplicationDataDirectory) ="/opt"
	String filename = File::getSpecialLocation(File::commonApplicationDataDirectory).getFullPathName() + "/Vaporizer2/" + settingsFile;
	if (read) {
		if (!File(filename).existsAsFile()) {
			File(filename).create(); //recursively create also directories
			File(filename).deleteFile();
			filename = getVSTPath() + "/VASTvaporizerSettings.xml"; //try compatibility
			migrate_legacy = true;
		}
	}
#endif

	return filename;
}
```
This would default to /opt/Vaporizer2/VASTvaporizerSettings.xml on Linux and 
C:\ProgramData\Vaporizer2\VASTvaporizerSettings.xml on Windows.
I see the benefit with that that it is the same for all Users including Admins.

**Comment by KottV** [comment]
regular user cannot write to `/opt` or `C:\ProgramData`
also, there may be a several users at the same machine. each one with it's own config

**Comment by VASTDynamics** [comment]
Hm, under Windows the installer runs as Admin. Then userApplicationDataDirectory or userDocumentsDirectory will in the installer default to the admin user. No idea how to get around that.

**Comment by KottV** [comment]
Maybe I missed smth. I think, installer shouldn't know any about user's path or touch it.
It installs binaries and factory presets.

When Vaporiser starts it creates it's directory with settings file in the user's path.

**Comment by VASTDynamics** [comment]
For the settings you are right - changed to:

```
String VASTAudioProcessor::getSettingsFilePath(bool read, bool &migrate_legacy) {
	//JUCE_WINDOWS	File::getSpecialLocation(File::userApplicationDataDirectory) ="C:\Users\<username>\AppData\Roaming\"
	//JUCE_MAC		File::getSpecialLocation(File::userApplicationDataDirectory) ="~/Library"
	//JUCE_LINUX	File::getSpecialLocation(File::userApplicationDataDirectory) ="/usr/share/"
	const String settingsFile = "VASTvaporizerSettings.xml";
	String filename = File::getSpecialLocation(File::userApplicationDataDirectory).getChildFile("Vaporizer2").getChildFile(settingsFile).getFullPathName();
	if (read) {
		if (!File(filename).existsAsFile()) {
			File(filename).create(); //recursively create also directories
			File(filename).deleteFile();
			filename = File(getVSTPath()).getChildFile(settingsFile).getFullPathName(); //try compatibility
			migrate_legacy = true;
		}
	}
	return filename;
}
```

**Comment by VASTDynamics** [comment]
@KottV 
I have implemented a symlink solution in the lates beta commit. It works on Windows. Could you pelase check if it works on Linux as well? That would be helpful.

**Comment by KottV** [comment]
> @KottV I have implemented a symlink solution in the lates beta commit. It works on Windows. Could you pelase check if it works on Linux as well? That would be helpful.

I haven't check yet. But it looks very uncommon to use symlinks from system dirs to user home folder.
Maybe it's worth not to rush and to find a more elegant solution, without any filesystem hacks.

**Comment by VASTDynamics** [comment]
It is the other way around - from user presets in home symlinked to factory in application folder. The good thing is that this works with presets, wavetables and wavs in the same way. I have tested it on macOS and it is fine. I know of two other VSTis that do it in the same way.Best regards,TobiasAm 20.10.2023 um 12:02 schrieb Konstantin Voinov ***@***.***>:﻿

@KottV I have implemented a symlink solution in the lates beta commit. It works on Windows. Could you pelase check if it works on Linux as well? That would be helpful.

I haven't check yet. But it looks very uncommon to use symlinks from system dirs to user home folder.
Maybe it's worth not to rush and to find a more elegant solution, without any filesystem hacks.

**Comment by KottV** [comment]
One problem of that approach - if you delete the package (uninstall) then these links goes dead in the user's directory. It's not fatal but not nice neither.

Also I faced some complaints from developers about keeping presets in `Documents` folder, and that proper way is to follow https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html and https://forum.juce.com/t/recommended-location-s-for-plugin-preset-xml-files/19435
so, for Linux it could be `~/.local/share/` and `~/Library/Audio/Presets/` for Macos which was told a case for sanboxed run

for Linux I wouldn't care but if it will be `~/Documents` we may see a lot of rant in issues after publish the code

**Comment by KottV** [comment]
Also current implementation with symlinks doesn't follow if user changes paths in the settings.

I found your previous suggestion about using `sPath.addIfNotAlreadyThere("/path/to/Factory");` is much more better for presets.
And maybe it's worth to consider how to improve tables/noises folders handling.

**Comment by VASTDynamics** [comment]
For tables and noises I use the OS FileChooserDialog. There is no way to make this work with multiple folders. The symlink approach has the advantage that it is the same for all three types. And it is flexible: when a user wants to move the factory he can just manually move it in the OS and create an alias.Best regards,TobiasAm 24.10.2023 um 23:38 schrieb Konstantin Voinov ***@***.***>:﻿
Also current implementation with symlinks doesn't follow if user changes paths in the settings.
I found your previous suggestion about using sPath.addIfNotAlreadyThere("/path/to/Factory"); is much more better for presets.
And maybe it's worth to consider how to improve tables/noises folders handling.

**Comment by KottV** [comment]
> For tables and noises I use the OS FileChooserDialog. There is no way to make this work with multiple folders. The symlink approach has the advantage that it is the same for all three types. And it is flexible: when a user wants to move the factory he can just manually move it in the OS and create an alias

OK, let's see :)

**Comment by KottV** [comment]
it must be either `~/Documents/Vaporizer2` or `~/.local/share/Vaporizer2`
so:
`File::getSpecialLocation(File::userDocumentsDirectory).("Vaporizer2").getChildFile("Presets").getFullPathName();`
or
`File::getSpecialLocation(File::userHomeDirectory).getChildFile(".local").getChildFile("share").getChildFile("Vaporizer2").getChildFile("Presets").getFullPathName();`

https://github.com/VASTDynamics/Vaporizer2/blob/44a5e03799a1fc4cc642611925a987c64df1e31b/VASTvaporizer/Source/Plugin/VASTAudioProcessor.cpp#L2991

**Comment by VASTDynamics** [comment]
> BTW I think we should follow common pattern for all platforms, if it's `Documents` then it should be `Documents` everywhere, if it's a user's data folder then so for every platform then.
Thank you. I have corrected to 
`File::getSpecialLocation(File::userHomeDirectory).getChildFile(".local").getChildFile("share")`
on Linux for now.
My research is so far that on Mac only userDocumentsDirectory really works in all cases as ~/library/* is mostly not accessible (invisible) for sandboxed applications. On Windows I believe [Users$USERNAME\Documents] is acceptable. So it is your take for Linux: is ~/Documents/Vaporizer2 OK? Then lets change it and make it symmetrical.

**Comment by KottV** [comment]
> So it is your take for Linux: is ~/Documents/Vaporizer2 OK? Then lets change it and make it symmetrical.

Let's make it symmetrical `userDocumentsDirectory` for Linux. There will be complains from the XDG standard followers, and they can change this path via settings.

**Comment by VASTDynamics** [comment]
Yes. Done. Thanks you.

**Comment by VASTDynamics** [comment]
This is solved and will be part of the next release.

**Comment by VASTDynamics** [comment]
@KottV I threw away the symlink approach. I just did not work with access rights. I went back to the simple approach of loading presets from two sources and copying wavetables and noises in subfolders of the user folders. I hope that is fine for you.

**Comment by KottV** [comment]
Do you mean that reason that we should be able to save wavetables/noises in the same folder where they were loaded?

**Comment by VASTDynamics** [comment]
I mean that instead of symlinks I implemented it now like this - as stated in the overview above:

Factory Noises: [$APPFOLDER]\Noises (read-only, no choice of folder)
User Noises: [Users$USERNAME\Documents]\Vaporizer2\Noises (write-enabled, contains copy of factory [userDocumentsDirectory]

So in the userDocumentsDirectory there is a Vaporizer2\Noises folder and it has a Factory subfolder. The Factory subfolder conrains copies of the files that are also in the app folder.

For presets it is not copied.

**Comment by KottV** [comment]
Sorry, I was unclear (I understand what has been changed).
I meant, what's the reason to place factory wt/noises in the user's directory? Is that just for convenience so the "load" button opens the default folder and this default directory should be writable also?

I'm asking because it's possible to consider some updates in GUI for that in the future. For example, have "load factory" and "load custom" buttons, or maybe have an array of folders with dropdown GUI  menu, so we can quickly switch them and then list with arrows:
![изображение](https://github.com/VASTDynamics/Vaporizer2/assets/4686351/d9b9dfaf-a610-47af-ae75-86de3e6343fd)
