### ISSUE TITLE
Crash on Macos Monterey 12.6.6 with VST3

### ISSUE THREAD

**Issue by gormanj** [VASTDynamics/Vaporizer2#2]
Crash on Macos Monterey 12.6.6 on a cMPro 5,1 with VST3 in Reaper and Standalone. VST2 works. I am using the SSE compatibility version. I've tried both 3.3.0 and 3.2.0. I've also tried logging in as a different user. EXC_BAD_INSTRUCTION (SIGILL). The VST3 works in another host (Komplete Kontrol).

**Comment by wpostma** [comment]
That's an intel CPU system?

**Comment by gormanj** [comment]
Yes, intel.
