### ISSUE TITLE
Linux: "At least one of your JUCE module paths is invalid!"

### ISSUE THREAD

**Issue by mikelupe** [VASTDynamics/Vaporizer2#22]
Hi. I'm not sure whether you were able to test on Linux or not - this mornings beta branch errors on some missing JUCE module when trying to export the Linux Makefile through Projucer (just before building Vaporizer2). 

\# Export Makefile 
./JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave ./VASTvaporizer/VASTvaporizer.jucer

Output:
```
./JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave ./VASTvaporizer/VASTvaporizer.jucer
Re-saving file: /home/user/Downloads/Audio_Plugins/Vaporizer2/Vaporizer2/VASTvaporizer/VASTvaporizer.jucer
Error when saving: At least one of your JUCE module paths is invalid!
Please ensure each module path points to the correct JUCE modules folder.
```
Seems to be one of the entries in VASTvaporizer.jucer after line 755. I've recursively pulled in the linked JUCE repo as well:
https://github.com/VASTDynamics/Vaporizer2/blame/19c7905cd5c1838c1e3cb3a656484010f534b90b/VASTvaporizer/VASTvaporizer.jucer#L755-L772

Maybe @KottV could shed some light about it. Switching back to his forked Linux repo builds ok.

Thanks for your efforts, much appreciated.
regards

**Comment by KottV** [comment]
Seems it was switched to global path's. I'll prepare a fix.
But it's possible to build using cmake now:
`cmake -B build -DCMAKE_BUILD_TYPE=Release`
`cmake --build build`

**Comment by mikelupe** [comment]
What would be the advantage of building with cmake?

**Comment by KottV** [comment]
it's more convenient, at least you don't have to use graphic application to configure the project
from user's POV there is no difference

**Comment by KottV** [comment]
[jucer_patch.tar.gz](https://github.com/VASTDynamics/Vaporizer2/files/13061782/jucer_patch.tar.gz)
could you try this patch?

**Comment by VASTDynamics** [comment]
How? I need more background info on the issue.Am 21.10.2023 um 22:29 schrieb Konstantin Voinov ***@***.***>:﻿
jucer_patch.tar.gz
could you try this patch?

**Comment by KottV** [comment]
it was for @mikelupe
in *nix it's just (inside Vaporizer2 folder): 
`tar xf jucer_patch.tar.gz`
`patch -p1 -i jucer.patch`

**Comment by mikelupe** [comment]
@KottV it's building now - looks good

**Comment by mikelupe** [comment]
@KottV sorry, it didn't run nicely through, my bad:

https://paste.debian.net/hidden/159a07be/

But i was true at least, that it exported the Makefile and launched compiling.

**Comment by KottV** [comment]
@mikelupe it will continue if you remove `inline` from
https://github.com/VASTDynamics/Vaporizer2/blob/612b5f69cb361f1d68d72808530492f83f97e33e/VASTvaporizer/Source/Plugin/VASTControls/VASTPitchbendSlider.cpp#L44

**Comment by mikelupe** [comment]
@KottV true - it then stumbled over the next one "VASTModwheelSlider". I guess there would be several "inline"s to be removed. I'll test anothertime.

**Comment by VASTDynamics** [comment]
The `inline` problem should be fixed in `beta` now. Please have a look.
@KottV The build, Cmake, code-sign, package to installer chain is now fully automated in one shot for Windows. That's cool. Thank you for the help. I did not commit the files for it as code-signing is not FOSS I would say. Next I will do the same for Windows. 
By the way: what would be a corresponding installer environment in Linux like Inno Setup on Windows and Packages on macOS?

**Comment by VASTDynamics** [comment]
@KottV And is there a point in distributing the LV2s with a Windows or MacOS installer?

**Comment by mikelupe** [comment]
#### Building
Cmake building with "cmake -B build -DCMAKE_BUILD_TYPE=Release ; cmake --build build" seems to work now.
It doesn't work with make though "./JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave ./VASTvaporizer/VASTvaporizer.jucer ; CONFIG=Release make -j16 -C ./VASTvaporizer/Builds/LinuxMakefile/".

#### Packaging
AFAIK under Linux you provide an (silently) installable .deb (Ubuntu/Debian), .rpm (RedHat/Fedora) package etc. OR a self contained VASTvaporizer2.AppImage (or FlatPack,Snap etc) executable which all are preconfigured with reasonable default values for e.g. preset paths etc. 
The user would on first application _launch_ be hinted to customize parameters in the in-app settings menu(s). So IMHO the philosophy usually is: there's no guided installer GUI with Linux packages, until you create a script to set some user defined values at installation-runtime, the script being launched by the package installer.

The default config is best to be generated on first launch, as @KottV hinted previously, as at runtime it's clear which user's profile should be configured. AllUsers Parameters can be set on installation w/o the need to know anything about the user. 

Please take all of this with a grain of salt, as I'm not at all a Linux packager (I used though to package Windows applications a long time ago). So I'm certain KottV will set all of this straigth.

**Comment by KottV** [comment]
> @KottV And is there a point in distributing the LV2s with a Windows or MacOS installer?

yes, why not?

**Comment by KottV** [comment]
> By the way: what would be a corresponding installer environment in Linux like Inno Setup on Windows and Packages on macOS?

I think it would be just a tar.gz archive with all binaries

**Comment by VASTDynamics** [comment]
This is solved and will be part of the next release.
