### ISSUE TITLE
Linux: Arp sequences keep retriggering during playback in Ardour

### ISSUE THREAD

**Issue by xard-dev** [VASTDynamics/Vaporizer2#28]
### Environment

- Ubuntu 22.04 64-bit
- Ardour 8.1.0 64-bit official build
- Vaporizer2 self built release version of commit e224cf890e3a411325ddf42793fc81cfb839dab4
- Tested plugin version: VST3

### Issue

When using tempo sync feature on Arpeggio notes each note is triggered multiple times when a playback is active. When the playback is not active the syncing works as expected and the notes do not get repeated.

### Other details

Tested the same build 64-bit version of Reaper 7.02 and tempo syncing feature worked as expected.

**Comment by VASTDynamics** [comment]
This is fixed in beta.

**Comment by VASTDynamics** [comment]
#25 
https://github.com/VASTDynamics/Vaporizer2/commit/5f2b526a6bb3888164c2f76477bce5e997f4fba3
https://github.com/VASTDynamics/Vaporizer2/commit/d25173e5573af7c5bf946058a501e31adc854dd4
https://github.com/VASTDynamics/Vaporizer2/commit/0633eb539fd0a232daa23c239df5db699779ad95
https://github.com/VASTDynamics/Vaporizer2/commit/2938a0c815b07e3c43e02b4b256114b1d1ae6022
