### ISSUE TITLE
Building on Linux (after 3.4 release)

### ISSUE THREAD

**Issue by mikelupe** [VASTDynamics/Vaporizer2#39]
Hello (hi @KottV )

After the official 3.4 release, I tried to build on Debian 12, and after it builds Projucer and resaves "VASTVaporizer.jucer", the step "CONFIG=Release make-C ./VASTvaporizer/Builds/LinuxMakefile/" leads to this:

```
[..]
Linking VASTvaporizer2 - Shared Code
Linking VASTvaporizer2 - VST3
Linking VASTvaporizer2 - Standalone Plugin

mkdir: missing Operand
„mkdir --help“ provides further information.
make: [Makefile:308: build/VASTvaporizer2.vst3/Contents/x86_64-linux/VASTvaporizer2.so] Error 1 (ignored)
cp: Missing file operand
„cp --help“ provides further information.
make: [Makefile:309: build/VASTvaporizer2.vst3/Contents/x86_64-linux/VASTvaporizer2.so] Error 1 (ignored)
make: Directory „/home/user/Downloads/Audio_Plugins/Vaporizer2/Vaporizer2/VASTvaporizer/Builds/LinuxMakefile“ being exited
```

The 308/309 line entries in the Makefile are:

```
        -$(V_AT)mkdir -p $(JUCE_VST3DESTDIR)
        -$(V_AT)cp -R $(JUCE_COPYCMD_VST3)
```
Is this expected for now? Or do I miss something in the building process?

Thanks for your efforts.

**Comment by VASTDynamics** [comment]
@KottV  Anyhow. There have been some last minutes fixes in 3.4.0. Maybe we need to rebuild the linuix packages for 3.4.0 as well. Sorry,

**Comment by KottV** [comment]
@VASTDynamics, done. No problem to trigger a rebuild+publish.
But we loose the versioning here. If you don't want to track "alphas", "betas" ans "RC" manually, I can suggest to use the git commit offset+hash versioning. So this build would be `3.4.0-4-gb671de1`

**Comment by mikelupe** [comment]
Thank you, it went well following [build_linux.sh](https://github.com/VASTDynamics/Vaporizer2/blob/beta/build_linux.sh)
