### ISSUE TITLE
User PC Keyboard layout and Midi notes

### ISSUE THREAD

**Issue by parduz** [VASTDynamics/Vaporizer2#45]
You can play notes not just clicking the MIDI Keyboard, but using the PC keyboard. But there's a minor problem, which seems to me is that it doesn't take in account the user keyboard layout.
I'm using an Italian keyboard
![image](https://github.com/VASTDynamics/Vaporizer2/assets/9556348/d38cfe44-7b82-4de1-968b-bc66ff50ab6b)
and the Y and Z keys are inverted (in respect to the notes played by the adjacent keys).

The VST should take the user keyboard layout in account.

**Comment by VASTDynamics** [comment]
Oha. Interesting.

**Comment by VASTDynamics** [comment]
Please check the pre-release - it should fix it. I have added an option in the settings.
[https://github.com/VASTDynamics/Vaporiz ... ag/v.3.4.1](https://github.com/VASTDynamics/Vaporizer2/releases/tag/v.3.4.1)
Or direct download for Windows (I am building macOS later): [https://github.com/VASTDynamics/Vaporiz ... _3.4.1.zip](https://github.com/VASTDynamics/Vaporizer2/releases/download/v.3.4.1/Vaporizer2_installer_win_3.4.1.zip)
