### ISSUE TITLE
macos ARM version crashes on preset switching

### ISSUE THREAD

**Issue by Jurek-Raben** [VASTDynamics/Vaporizer2#46]
Hi,

many thanks for the arm version, makes the KVR OSC round much more attractive :)

I noticed that the plugin kind of "randomly" quits on preset change. Couldn't nail it down to always reproducable steps, but this should work:

Steps to reproduce

1. Load arm build on M1pro or similar, load into Renoise latest version
2. Go to preset manager, start to play and then switch presets wildly, for about a minute
3. Especially the presets "BS Morser" and "Macro Riser" tend to crash, so make sure to come back to these two presets often
4. Sudden quit of Renoise should happen. Log file sadly shows nothing due sudden quit nature.

**Comment by VASTDynamics** [comment]
Thanks. I will check asap.

**Comment by VASTDynamics** [comment]
I could not find the same problem here in a quick test. Just in case - if you have downloaded and installed an early on Saturday then it would be helpful for me if you can redownload, reinstall and retest. There has been a related last minute change that is fixed meanwhile.

**Comment by VASTDynamics** [comment]
Ah, I just had the same in Renoise. Let's see.

**Comment by VASTDynamics** [comment]
If you have a crashreport.log file in your /applications/Vaporizer2 folder it would be great if you could paste the content here.

**Comment by VASTDynamics** [comment]
------------------------------------------------------
0   VASTvaporizer2                      0x0000000120101c65 _ZN18VASTAudioProcessor12crashHandlerEPv + 5381
1   VASTvaporizer2                      0x000000011fdb3529 _ZN4juceL11handleCrashEi + 9
2   libsystem_platform.dylib            0x00007ff8054d05ed _sigtramp + 29
3   ???                                 0x0000600005a56088 0x0 + 105553210990728
4   VASTvaporizer2                      0x00000001200c1b08 _ZN15VASTSynthesiser12renderVoicesER15sRoutingBuffersii + 23896
5   VASTvaporizer2                      0x00000001200a1015 _ZN9CVASTPoly18processAudioBufferER15sRoutingBuffersRN4juce10MidiBufferE + 11845
6   VASTvaporizer2                      0x00000001200da7c6 _ZN14CVASTXperience18processAudioBufferERN4juce11AudioBufferIfEERNS0_10MidiBufferEibdbdd + 12006
7   VASTvaporizer2                      0x00000001200deacc _ZN18VASTAudioProcessor12processBlockERN4juce11AudioBufferIfEERNS0_10MidiBufferE + 2204
8   VASTvaporizer2                      0x000000011fcd7bf6 _ZN4juce17JuceVST3Component7processERN9Steinberg3Vst11ProcessDataE + 9558
9   Renoise                             0x00000001029d2d54 _ZN4asio6detail16service_registry6createINS0_23reactive_socket_serviceINS_2ip3udpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv + 831650
10  Renoise                             0x00000001029915b0 _ZN4asio6detail16service_registry6createINS0_23reactive_socket_serviceINS_2ip3udpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv + 563454
11  Renoise                             0x00000001028d790c Renoise + 5548300
12  Renoise                             0x00000001028d776f Renoise + 5547887
13  Renoise                             0x00000001028d95cc Renoise + 5555660
14  Renoise                             0x000000010297dd01 _ZN4asio6detail16service_registry6createINS0_23reactive_socket_serviceINS_2ip3udpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv + 483407
15  Renoise                             0x000000010291dfd0 _ZN4asio6detail16service_registry6createINS0_23reactive_socket_serviceINS_2ip3udpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv + 90910
16  Renoise                             0x0000000102924ca2 _ZN4asio6detail16service_registry6createINS0_23reactive_socket_serviceINS_2ip3udpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv + 118768
17  Renoise                             0x0000000102924e68 _ZN4asio6detail16service_registry6createINS0_23reactive_socket_serviceINS_2ip3udpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv + 119222
18  Renoise                             0x000000010291c4f3 _ZN4asio6detail16service_registry6createINS0_23reactive_socket_serviceINS_2ip3udpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv + 84033
19  Renoise                             0x0000000102e5a5d2 _ZN4asio6detail16service_registry6createINS0_23reactive_socket_serviceINS_2ip3udpEEENS_10io_contextEEEPNS_17execution_context7serviceEPv + 5581088
20  libsystem_pthread.dylib             0x00007ff8054a31d3 _pthread_start + 125
21  libsystem_pthread.dylib             0x00007ff80549ebd3 thread_start + 15

------------------------------------------------------

------------------------------------------------------

**Comment by Jurek-Raben** [comment]
Sadly there is no such file here... Hm, is there maybe some kind of race condition or so happening here, so it only will happen on ARM machines? Is this synth using multicore? Are the voices propery dallocated before loading a new preset? Should be input prevented for the time of loading or so? Really only wild guesses  😅

**Comment by Jurek-Raben** [comment]
Hi, this does not seem to be fixed in the new 3.4.1 release sadly... I simply switched like 10 presets and constantly playing, and Renoise again force-quit...
