### ISSUE TITLE
Conflicting license files in the repo

### ISSUE THREAD

**Issue by mbrukman** [VASTDynamics/Vaporizer2#5]
First of all, thank you very much for sharing this project with us!

I just wanted to confirm the licensing as there are multiple files, and some of them are duplicating each other and some are in conflict with each other and the `README.md` file.

Specifically, this repo has 3 license files:

* [`COPYING`](https://github.com/VASTDynamics/Vaporizer2/blob/4d1eea7bfeab6dfa544209873e7ed09a1773d178/COPYING) – this seems to be a custom license based on MIT license, but includes an additional clause which makes it non-OSS:

https://github.com/VASTDynamics/Vaporizer2/blob/4d1eea7bfeab6dfa544209873e7ed09a1773d178/COPYING#L11-L13

* [`COPYING.GPLv3`](https://github.com/VASTDynamics/Vaporizer2/blob/4d1eea7bfeab6dfa544209873e7ed09a1773d178/COPYING.GPLv3) – looks like a GPL v3 license
* [`LICENSE`](https://github.com/VASTDynamics/Vaporizer2/blob/4d1eea7bfeab6dfa544209873e7ed09a1773d178/LICENSE) – looks like a GPL v3 license

---

However, the [`README.md`](https://github.com/VASTDynamics/Vaporizer2/blob/4d1eea7bfeab6dfa544209873e7ed09a1773d178/README.md?plain=1#L15) says the project is under the GPL v3 license:

https://github.com/VASTDynamics/Vaporizer2/blob/4d1eea7bfeab6dfa544209873e7ed09a1773d178/README.md?plain=1#L15

---

This brings up several questions:

* Is the `COPYING` file here extra and should it be removed to avoid confusion?
* Do you need to both `LICENSE` and `COPYING.GPLv3` which are identical license files? Would just having `LICENSE` suffice?

**Comment by VASTDynamics** [comment]
Yes, you are right. [COPYING.GPLv3] and [COPYING] have been removed now.

**Comment by mbrukman** [comment]
Thanks, @VASTDynamics!
