### ISSUE TITLE
any hints on how to build the code

### ISSUE THREAD

**Issue by teknopaul** [VASTDynamics/Vaporizer2#50]
build_linux.sh borkes because JUCE directory is empty.
I have JUCE development libs locally, I shouldn't need a dedicated version to build with JUCE as a dependency?
If the build requires some very specific JUCE, I would need to know which version and where to get it.

**Comment by VASTDynamics** [comment]
First of all: you are aware that there are prebuild packages and installers also for linux available? (see https://github.com/VASTDynamics/Vaporizer2/releases/tag/v3.4.0)

In case you want to build on your own. JUCE, AnaMark-Tuning-Library and muFFT are own GitHub repositories that are submodules in Vaporizer2. So to checkout you need to do somethuing like:

create a suitable folder and cd into it
```
git clone https://github.com/VASTDynamics/Vaporizer2.git
cd Vaporizer2
git submodule update --init --recursive

```
And then for Linux
`./build_linux.sh`

**Comment by teknopaul** [comment]
OK  thanks I didnt see those Linux links  there are master README.md does not have lins for Linux.

I still want to build it because I'm looking at integrating it into LMSS so I can use LMMS control automation to control it.

After setting -DUSE_SYSTEM_JUCE=ON in the firest call to cmake I can compile but it wont link

/usr/bin/ld: /tmp/cceTLFQd.ltrans0.ltrans.o: in function `juce::StandalonePluginHolder::createPlugin()':
<artificial>:(.text+0x26d6): undefined reference to `createPluginFilter()'


Is that a missing cmake file for juce?

**Comment by teknopaul** [comment]
OK sorry , gotcha

git submodule update --init --recursive

is missing from the build script

**Comment by teknopaul** [comment]
Then cmake fails but it tries to build anyway

you might want to add set -e to the bash script

**Comment by teknopaul** [comment]
in GNU Linux such instructions live in the INSTALL file inthe root of the project, not sure where it should be for cross platform projects

**Comment by KottV** [comment]
@teknopaul yes, build script and instructions require some attention

**Comment by teknopaul** [comment]
Build successful and looking at code, cheers geeza
