### ISSUE TITLE
Line up tags, versions and Changelog.

### ISSUE THREAD

**Issue by KottV** [VASTDynamics/Vaporizer2#51]
Hi Tobias!

At this moment each Vaporizer repository tag is different
v.3.4.1
v3.4.0
3.4.0

which is confusing, as they should be v3.4.1 or 3.4.1.
Also 3.4.2 is already in the `VERSION` of beta branch and in Pre-release, but there is no such tag.
And it would be nice and to have `CHANGELOG.md`.

**Comment by VASTDynamics** [comment]
I will use all tags in format "v3.1.2" going forward.
