### ISSUE TITLE
presets saving

### ISSUE THREAD

**Issue by ThomasTrupiano** [VASTDynamics/Vaporizer2#52]
when you save a preset with an automated parameter, the parameter is saved to the instant value

exemple :
if you use a value set from 0 
without automation, it will be saved from 0
with an automation, it will be saved from the instant value

**Comment by VASTDynamics** [comment]
What is an instant value?

**Comment by VASTDynamics** [comment]
This is standard plugin behaviour. If you automate from the DAW then you change parameter values.
