### ISSUE TITLE
new saved presets are missing on the list

### ISSUE THREAD

**Issue by ThomasTrupiano** [VASTDynamics/Vaporizer2#53]
i tried to reload the vapo inside the daw
i tried to close and open the daw again

my saved preset appears inside the windows folder 
but it doesn't appear inside the vapo list

![presets miss](https://github.com/VASTDynamics/Vaporizer2/assets/153279215/163d1dc2-92c1-41fa-aaec-8c97cef388de)
![presets miss 2](https://github.com/VASTDynamics/Vaporizer2/assets/153279215/048061e3-de01-470d-beaa-715c11fc06c5)

**Comment by ThomasTrupiano** [comment]
after saving a second preset, the first preset now appears on the vapo list
the second still missing

**Comment by ThomasTrupiano** [comment]
my presets folder is :
C:\Program Files\Vaporizer2\Presets

this folder is here but empty :
C:/Program Files/Vaporizer2 and in C:/users//AppData/Roaming/Vaporizer2

**Comment by VASTDynamics** [comment]
The file is named VASTvaporizerSettings.xml

**Comment by ThomasTrupiano** [comment]
ah yes sorry i found it
there are two files in the same folder
![preset files](https://github.com/VASTDynamics/Vaporizer2/assets/153279215/ae487ad3-8aa2-4cc8-9573-ea4307ede9c4)

**Comment by ThomasTrupiano** [comment]
![image](https://github.com/VASTDynamics/Vaporizer2/assets/153279215/2ca9f7f1-7fc3-435b-aa50-49d16cc11b6e)
