### ISSUE TITLE
Crash in bitwig 5.0.11

### ISSUE THREAD

**Issue by ElVicente** [VASTDynamics/Vaporizer2#58]
https://kdrive.infomaniak.com/app/share/795671/0fddd7e9-2274-4d9a-9400-e899abec94ea

This preset will crash when I press play on bitwig.
(win 10)

**Comment by VASTDynamics** [comment]
Yes, I am sorry. I had noticed the same. There is a problem with Mono / Legato mode in 3.4.3. that I will fix in a couple of hours. I have removed 3.4.3 installers for now.

**Comment by VASTDynamics** [comment]
Hi, could you download and install again from here?

https://github.com/VASTDynamics/Vaporizer2/releases/tag/v.3.4.3

I have fixed it and I do not get this issue on my local systems anymore.

Thanks.

 

From: ElVicente ***@***.***> 
Sent: Monday, 11 December 2023 09:50
To: VASTDynamics/Vaporizer2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VASTDynamics/Vaporizer2] Crash in bitwig 5.0.11 (Issue #58)

 

https://kdrive.infomaniak.com/app/share/795671/0fddd7e9-2274-4d9a-9400-e899abec94ea

This preset will crash when I press play on bitwig.
(win 10)

**Comment by ElVicente** [comment]
I tried (downloaded two times),
But when I open the zip file I got an error message telling me the file is
invalid...

Le lun. 11 déc. 2023 à 14:34, VAST Dynamics ***@***.***> a
écrit :

**Comment by ElVicente** [comment]
Well using 7zip did finally let me uncompress the 3.4.3 file.

When turning on legato on a mono patch the gui and all bitwig become extremely laggy.
