### ISSUE TITLE
Linux builds for 3.4.3

### ISSUE THREAD

**Issue by VASTDynamics** [VASTDynamics/Vaporizer2#60]
@KottV  There is a request on KVR to add Linux builds for 3.4.3 to the release note. Would you be so kind? Thank you.

**Comment by KottV** [comment]
OBS (openSUSE Build Service) links will be the same
anyway:

https://github.com/KottV/Vaporizer2/releases/tag/3.4.3

**Comment by VASTDynamics** [comment]
Thanks
