### ISSUE TITLE
Using mod wheel via mouse in plug-in and stand alone sound is EXTREMELY glitchy

### ISSUE THREAD

**Issue by bcario** [VASTDynamics/Vaporizer2#62]
When I use my mouse to rotate the mod wheel in the plug-in (AU and VST3 - did not test formats) and in the stand alone, the sound produced is very glitchy - sounds kind of like a turning a dirty volume control. Using the mod wheel on my MIDI controller works as expected - no glitching at all. Wondering if it might be some sort of graphics issue. Not a big issue - but it is something I sometimes do on my laptop when auditioning sounds with no MIDI controller connected.

14" M1 MacBook Pro, 32GB. Sonoma 14.2 (also happened under 14.1.2)

VAST 3.4.3

**Comment by VASTDynamics** [comment]
Yes, thank you. A simple bug. This is fixed in next release.

**Comment by VASTDynamics** [comment]
https://github.com/VASTDynamics/Vaporizer2/commit/75cbfb95191dc0f70096afa60731c23b9c961851
