### ISSUE TITLE
mpe broken

### ISSUE THREAD

**Issue by ElVicente** [VASTDynamics/Vaporizer2#64]
Mpe notes pitch bends will not initialise correctly on each notes.
Instead it will initiate at corresponding midi channel last note off pitch value.

**Comment by VASTDynamics** [comment]
Hi, could you please describe a bit more detailed on how to reproduce the problem? Thank you!

**Comment by ElVicente** [comment]
I'll try again :)

If I play on my linnstrument  a C then bend it down 3 semitones and release
it.

Next C I'll will be okay (another midi channel I think).
But then the C after that will initiate with that same -3 semitone although
I'm not bending it at all. It'll stay there until I'll start to make a bend
move where it will catch the 'correct' bend value.

Hope it's clearer.

I'm on bitwig win10.

Le sam. 23 déc. 2023 à 18:17, VAST Dynamics ***@***.***> a
écrit :

**Comment by KottV** [comment]
Is it possible to capture the data in some common DAW and paste here?

**Comment by ElVicente** [comment]
I'm on vacation with family until the 27'th.
Then I'll try to do that !
All the best
Vincent

**Comment by VASTDynamics** [comment]
I think I found the problem and I hope it is fixed in the next release. Please verify. Thank you.

**Comment by ElVicente** [comment]
Thank you
I'll check for sure and let you know !

Le lun. 25 déc. 2023 à 14:20, VAST Dynamics ***@***.***> a
écrit :

**Comment by VASTDynamics** [comment]
Please check:
https://github.com/VASTDynamics/Vaporizer2/releases/tag/v3.4.5

**Comment by ElVicente** [comment]
Finally could fire it ut today. Seems way better now, thank you !

Still, I don't know if it's related but a lot of my patches first notes still won't play correctly when I open my daw . After one 'faulty' note, everything become ok, and I can play the project from the begining without error (but not render offline)
The error often sound like a mismatched pitch bend setting going way out of range.
