### ISSUE TITLE
clap-juce-extensions submodule is not initialized

### ISSUE THREAD

**Issue by KottV** [VASTDynamics/Vaporizer2#68]
Hi,

when you do `git clone --recursive`  the `clap-juce-extensions` is not pulled, seems that it was not properly added to source tree:

![изображение](https://github.com/VASTDynamics/Vaporizer2/assets/4686351/76d0e851-09fe-4891-805a-41c5492492f9)

**Comment by VASTDynamics** [comment]
Can you please check again? Thanks!

**Comment by KottV** [comment]
all is good, thanks

**Comment by VASTDynamics** [comment]
@KottV 
In CMakeLists.txt of clap-juce-extension I have to add;

```
target_compile_options(clap_juce_extensions PUBLIC
 "/MT")

```
to have all libraries compiled as static libraries. 
Do you by chance know how I can do theis without modifying the clap-juce-extension files?
Thanks.

**Comment by KottV** [comment]
How does it looks, I mean dynamic clap libraries? On Linux it works as usual JUCE static linked module without any separate libraries.

Maybe you can try to pass `-DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_STATIC_LIBS:BOOL=ON` arguments to cmake.
