### ISSUE TITLE
First note played after DAW launch out of tune on MPE patch 

### ISSUE THREAD

**Issue by VASTDynamics** [VASTDynamics/Vaporizer2#69]
First note played after DAW launch out of tune on MPE patch

**Comment by ElVicente** [comment]
This happens to a lot patches here, even non mpe patches : 
https://kdrive.infomaniak.com/app/share/795671/00e17e6b-6380-49b7-b602-c06f3f76e469

**Comment by ElVicente** [comment]
Here's a mpe patch where it happens every time after turning on Bitwig's Audio engine
https://kdrive.infomaniak.com/app/share/795671/cf617735-5c95-4b67-a018-1d25a87284dc

**Comment by VASTDynamics** [comment]
This should be fixed in 3.4.8.
