### ISSUE TITLE
Not playing reliably if gui is closed

### ISSUE THREAD

**Issue by ElVicente** [VASTDynamics/Vaporizer2#71]
This patch has this strange behavior...

https://kdrive.infomaniak.com/app/share/795671/2d0c0e7d-1499-4c6e-9a66-21746f32e22a

**Comment by VASTDynamics** [comment]
Hi, what dies "reliably" mean? I tested in FL Studio and I get the same sound with GUI visible or minimzed.

**Comment by ElVicente** [comment]
Sorry for not being clear, that was a typo, I meant not 'fire' reliably.
It means I will only get a small burst, not the long tail.
Note that If I play several time the note It will then works, but nit after
a long silence.
If gui is open it will play correctly each time though.

Le mer. 3 janv. 2024 à 11:13, VAST Dynamics ***@***.***> a
écrit :

**Comment by VASTDynamics** [comment]
Hm, I tested on FL studio and Bitwig with VST3. What are you using? Can you maybe create a video?? Thx
