### ISSUE TITLE
Crash when opening in Ardour 

### ISSUE THREAD

**Issue by REIS0** [VASTDynamics/Vaporizer2#73]
Hello just installed vaporizer 3.4.5 from .rpm in Fedora 39 but every time I try to open it in Ardour 8.* I get crashes, not sure what's happening. Here's the log:
```
Ardour: [INFO]: Loading bindings from /opt/Ardour-8.2.0/etc/ardour.keys
Loading ui configuration file /opt/Ardour-8.2.0/etc/clearlooks.rc
Set cursor set to default
start clocking
Setting time domain
start clocking
/usr/include/c++/13/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = juce::AudioPlayHead::PositionInfo; _Dp = std::_Optional_base<juce::AudioPlayHead::PositionInfo, true, true>]: Assertion 'this->_M_is_engaged()' failed.
fish: Job 1, 'Ardour8' terminated by signal SIGKILL (Forced quit)
```

**Comment by VASTDynamics** [comment]
@KottV Could you have a look? I suspect that this is related to the C++13/C++17/C++20 topic since std::Optional is C++17 - but it was introduced by JUCE in that way.

**Comment by KottV** [comment]
@REIS0 
Hi, what plugin format?

**Comment by REIS0** [comment]
@KottV LV2

**Comment by KottV** [comment]
@REIS0 does it crash with other formats? 
I enabled debug builds in OBS [see](https://build.opensuse.org/projects/multimedia:proaudio/packages/vaporizer2/repositories/Fedora_39/binaries) , so you can install lv2-vaporizer2-debuginfo and try to trace it with GDB.

Also would be helpful if you check GH builds from here: https://github.com/KottV/Vaporizer2/releases/tag/3.4.8

**Comment by REIS0** [comment]
@KottV the tar version you sent works, no crashes. Also when I downloaded the 3.4.5 VST3 version ardour didn't seem to recognize for some reason.

**Comment by KottV** [comment]
It should be fixed now, I tested with `lv2-vaporizer2` and `vst3-vaporizer2` in Fedora 39
This problem caused by `-Wp,-D_GLIBCXX_ASSERTIONS` flag set in Fedora build by default, and this drops an assert in `juce::AudioPlayHead::TimeSignature` somehow.

I just simply removed this CXX flag for now from Fedora receipt.

**Comment by REIS0** [comment]
I'll be closing it now since it's working and we know the error.
