### ISSUE TITLE
How does one import a .vvp file?

### ISSUE THREAD

**Issue by windowsrefund** [VASTDynamics/Vaporizer2#77]
It seems there's some assumption in place that users will be saving their exports to a "Presets" directory. In my case, this fixed "Presets" directory is set as ~/.Vaporizer2/Presets

From a data recovery perspective, I would never use a material-agnostic location like this to store work. Best practices would be to keep related material together. To that end, I've used the "Save" button to export a custom patch to an appropriate location in my file system but I see no "Load" or "Import" button.

How does one import a .vvp file? Are people just manually copying to their static "Presets" directory?

**Comment by VASTDynamics** [comment]
Hm, yes. Presets are assumed to be located in the preset folder (factory or user). It might be reasonable to add a load .vvp function. But you could also use the save / load state function of your DAW. I will add it to the todo list.

**Comment by VASTDynamics** [comment]
In the newest version 2.5.0 I have implemented file drag an drop to the header component. So you can now drag a .vvp file and drop it over the preset display to load this rpedet file. Maybe as a first step.
