### ISSUE TITLE
Scale & Microtonal

### ISSUE THREAD

**Issue by nowgad** [VASTDynamics/Vaporizer2#85]
Is it possible to add Scale & Microtonal features?

**Comment by VASTDynamics** [comment]
You have seen this?
<img width="962" alt="Bildschirmfoto 2024-03-27 um 09 36 07" src="https://github.com/VASTDynamics/Vaporizer2/assets/35850267/ded0f0fc-cc84-4491-ad94-75327d3d2a40">

[https://www.mark-henning.de/files/am/Tuning_File_V2_Doc.pdf](https://www.mark-henning.de/files/am/Tuning_File_V2_Doc.pdf)
